blank_issues_enabled: false
contact_links:
  - name: ğŸ“— FAQ
    url: https://duskmoonui.com/docs/faq/
    about: Read about common problems and how to fix
  - name: ğŸ” Search in Discussions
    url: https://github.com/duskmoon-dev/duskmoon-ui/discussions?discussions_q=
    about: First see if there's an existing topic in Discussions.
  - name: ğŸ” Search in Issues
    url: https://github.com/duskmoon-dev/duskmoon-ui/issues?q=is%3Aissue
    about: If you found a bug, first see if there's an existing issue about it.
  - name: â“ Ask a new question in Discussions
    url: https://github.com/duskmoon-dev/duskmoon-ui/discussions/new?category=q-a
    about: If you have a new question and you couldn't find answers.
  - name: ğŸ’¡ Ideas / Feature request
    url: https://github.com/duskmoon-dev/duskmoon-ui/discussions/new?category=ideas-feature-requests
    about: If you want to suggest a new idea or if you want a new feature to be added to duskmoonUI, let's talk about it in Discussions forum
